version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: php-fpm.Dockerfile   # <— point to your file
    container_name: laravel_app
    env_file: .env
    depends_on:
      - db
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html
    networks:
      - laravel_net

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_net

networks:
  laravel_net:
    driver: bridge

volumes:
  db_data:
